
import { supabase } from '@/integrations/supabase/client';

export class JobService {
  static async createJob(displayId: string, userId: string, propertyUrl: string): Promise<void> {
    console.log('Attempting to create job:', { displayId, userId, propertyUrl });
    
    const { error } = await supabase
      .from('jobs')
      .insert({
        display_id: displayId,
        user_id: userId,
        property_url: propertyUrl,
        status: 'analyzing',
        current_step: 1
      });

    if (error) {
      console.error('Error creating job in database:', error);
      throw new Error(`Failed to create job: ${error.message}`);
    }
    
    console.log('Job created successfully in database');
  }

  static generateDisplayId(): string {
    // This will be auto-generated by the database trigger
    return '';
  }

  static async getJobByDisplayId(displayId: string) {
    const { data, error } = await supabase
      .from('jobs')
      .select('*')
      .eq('display_id', displayId)
      .maybeSingle();

    if (error) {
      console.error('Error fetching job by display ID:', error);
      return null;
    }

    return data;
  }
}
