// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmcxcssjewqtcsxsffzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptY3hjc3NqZXdxdGNzeHNmZnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTIyNDAsImV4cCI6MjA2NDUyODI0MH0.4gBsm82VbIETFD1W4GvbwntiuejoxI2Zl9fUKbr_Ogg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);